### ISSUE TITLE
set height from top of viewport

### ISSUE THREAD

**Issue by packytagliaferro** [alamcordeiro/vue-smooth-scroll#1]
Can you set the height from the top like `100px` to compensate for navigation header? So if I scroll to a `<h2>` tag I can still see the text and its not covered up by a `fixed` header?

**Comment by krystalcampioni** [comment]
@alamcordeiro thanks a lot for this package 😄 I noticed that the npm package is not up to date with these changes, allowing us to use the offset. Could you please publish 1.0.13 to npm?

**Comment by ocordeiro** [comment]
Ohh really. thank you.
Done, published 1.0.13

**Comment by krystalcampioni** [comment]
awesome, thanks! :D
