### ISSUE TITLE
What's the difference with vue-smoothscroll?

### ISSUE THREAD

**Issue by kodekrendel** [alamcordeiro/vue-smooth-scroll#3]
Hi there.
I wonder, whats the difference between this repo and https://github.com/Teddy-Zhu/vue-smoothscroll

**Comment by mvanroon** [comment]
I believe vue-smooth-scroll is to be used directly on anchors in order to scroll to another element, while smooth-scroll scrolls to a given element as soon as it appears

**Comment by kodekrendel** [comment]
@mvanroon I literally see no difference in your words.

**Comment by mvanroon** [comment]
vue smoothscroll: if element with smoothscroll is present in DOM, scroll to that element
vue smooth-scroll: when clicking on an anchor with smooth-scroll, scroll to the element that the anchor refers to

**Comment by kodekrendel** [comment]
That literally equals, no? Ha-ha.

**Comment by kodekrendel** [comment]
vue smoothscroll: anyway you WILL use anchors
vue smooth-scroll: anyway element MUST be present in DOM

**Comment by mvanroon** [comment]
I give up 😫  maybe try installing both components and find out what the difference is yourself

**Comment by kodekrendel** [comment]
OK now I see what you mean. `v-on:click="clickfunc()"` in smoothscroll, not anchors. Thanks!
